Updated pki script

diff --git a/projects/rancher/install b/projects/rancher/install
--- a/projects/rancher/install
+++ b/projects/rancher/install
@@ -1,24 +1,31 @@
 #!/bin/bash
 
 minikube_check=0
-cert_path="../../tls/certs"
-certs=(
- "server-wildcard.crt"
- "server-wildcard.key"
- "ca-cert.pem"
-)
+pass=1
 
-for cert in "${certs[@]}"; do
- if [[ ! -f "$cert_path/$cert" ]]; then
-  echo "Certficate not found: $cert"
-  exit 1
+declare -A pki
+
+pki["CRT"]="../../tls/certs/server-wildcard.crt"
+pki["KEY"]="../../tls/certs/server-wildcard.crt"
+pki["CA"]="../../tls/certs/ca-cert.pem"
+
+for cert in "${!certs[@]}"; do
+ if [[ ! -f "${certs[$cert]}" ]]; then
+  echo -e "\e[91m(!)\e[0m Certficate not found: ${certs[$cert]}"
+  fail=1
  fi
 done
+
+if ! (( pass )); then
+ echo "(i) Generating new certificats..."
+ ../../1-create-testable-pki-files
+fi
 
 if ((minikube_check == 1)); then
  minikube start \
   --kubernetes-version=v1.34.0 \
   --memory=12000 \
+  --disk-size=40g \
   --cpus=8
 fi
 
@@ -35,8 +42,8 @@ kubectl create namespace cattle-system --dry-run=client -o yaml | kubectl apply 
 
 # Create the Rancher TLS secret
 kubectl create secret tls tls-rancher-ingress \
- --cert="$cert_path/server-wildcard.crt" \
- --key="$cert_path/server-wildcard.key" \
+ --cert="${certs[CRT]}" \
+ --key="${certs[KEY]}" \
  --namespace cattle-system \
  --dry-run=client -o yaml | kubectl apply -f -
 
@@ -54,7 +61,7 @@ kubectl annotate secret tls-rancher-ingress -n cattle-system \
 
 # Create the Rancher Ca-Cert
 kubectl create secret generic tls-ca \
- --from-file=cacerts.pem="$cert_path/ca-cert.pem" \
+ --from-file=cacerts.pem="${certs[CA]}" \
  --namespace cattle-system \
  --dry-run=client -o yaml | kubectl apply -f -
 
