Updated builder file for Dockerfile and terraform

diff --git a/resources/projects/coder/install-coder-v2/resources/addons/filebrowser/docker/build b/resources/projects/coder/install-coder-v2/resources/addons/filebrowser/docker/build
--- a/resources/projects/coder/install-coder-v2/resources/addons/filebrowser/docker/build
+++ b/resources/projects/coder/install-coder-v2/resources/addons/filebrowser/docker/build
@@ -3,14 +3,54 @@
 # exit immediately
 set -e
 
-ENV="minikube"
-IMAGE="coder-filebrowser"
-TAG="latest"
+environment="minikube"
+image_name="coder-filebrowser"
+image_tag="latest"
 
-if [[ "$ENV" == "minikube" ]]; then
+function process-args {
+
+ local args=$(getopt -o e:t:n: -l environment:image_name:image_tag: -- "$@")
+
+ eval set -- "$args"
+ while true; do
+
+  case "$1" in
+  -e | --environment)
+   if [[ "$2" == "minikube" || "$2" == "k8" ]]; then
+    environment="$2"
+    shift 2
+   else
+    echo "Error: Environment must be either 'minikube' or 'k8'." >&2
+    return 1
+   fi
+   ;;
+  -t | --tag)
+    image_tag="$2"
+    shift 2
+   ;;
+  -n | --image-name)
+    image_name="$2"
+    shift 2
+   ;;
+  --)
+   shift
+   break
+   ;;
+  *)
+   echo "Error: Invalid argument parsed." >&2
+   return 1
+   ;;
+  esac
+
+ done
+
+ echo "Environment set to: $environment"
+}
+
+if [[ "$environment" == "minikube" ]]; then
  echo "Building image for Minikube use..."
- minikube image build -t "$IMAGE":"$TAG" .
+ minikube image build -t "$image_name":"$image_tag" .
 else
- echo "Building image: $IMAGE:$TAG"
- docker image build -t "$IMAGE":"$TAG" .
+ echo "Building image: $image_name:$image_tag"
+ docker image build -t "$image_name":"$image_tag" .
 fi
